from database import Database

db = Database("smdb", True)
db.select("course", "*")
print("department ok")
# print("-----------------------------")
# print("Create hash index")
# db.create_index('department', index_type="HashIndex")
print("-----------------------------")
print("Search with hash index for department: ")
db.select('department', '*', 'dept_name==Finance')
# print("-----------------------------")
# print("Create hash index")
# db.create_index('course', index_type="HashIndex")
print("-----------------------------")
print("Search with hash index for course: ")
db.select('course', '*', 'course_id==FIN-201')